steps:
  # Build the Go binary
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'my-app', '.']
    env: ['PROJECT_ROOT=hello']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'build', '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-go-app:$SHORT_SHA', '-f', Dockerfile, '.']

  #  List Docker images (optional)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['image', 'ls']

  # List Docker images (optional)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['images', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-go-app:$SHORT_SHA']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['image', 'push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-go-app']

  # Deploy to Cloud Run (optional)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'go-lang-quick-app' # Name of your Cloud Run service
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-go-app:$SHORT_SHA'
      - '--region'
      - 'asia-southeast1' # Specify your desired region
      - '--platform'
      - 'managed'
images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-go-app:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY